import { Shield, Lock, Search, Mail, Phone, MapPin, Presentation } from "lucide-react"
import { IconUser, IconDeviceDesktop } from "@tabler/icons-react"

export const servicesDetail = [
  {
    slug: "penetration-testing",
    title: "Penetration Testing & Ethical Hacking",
    description: "We simulate real-world attacks to uncover vulnerabilities before malicious actors do.",
    shortDescription: "Simulate real-world attacks to find vulnerabilities early",
    icon: Shield,
    color: "text-[#E11D2E]",
    glowClass: "neon-glow-red",
    fullContent: `Our penetration testing services provide comprehensive security assessments through controlled, authorized attacks. We simulate the techniques used by real adversaries to identify exploitable vulnerabilities in your systems, applications, and networks.`,
    benefits: [
      "Identify real vulnerabilities before attackers do",
      "Understand actual impact and business risk",
      "Detailed remediation recommendations",
      "Compliance with regulatory requirements",
    ],
    process: [
      "Reconnaissance & Planning",
      "Scanning & Enumeration",
      "Vulnerability Analysis",
      "Exploitation & Post-Exploitation",
      "Report & Recommendations",
    ],
    portfolio: [
      {
        id: 1,
        title: "Fortune 500 Banking Infrastructure",
        client: "Major Financial Institution",
        result: "Discovered 12 critical vulnerabilities, helped prevent potential $50M+ breach",
        methodology: "Black-box network penetration test",
      },
      {
        id: 2,
        title: "E-commerce Platform Security",
        client: "Online Marketplace",
        result: "Found API authentication bypass, credential exposure",
        methodology: "White-box web application testing",
      },
      {
        id: 3,
        title: "Cloud Infrastructure Assessment",
        client: "SaaS Provider",
        result: "Identified misconfigured S3 buckets exposing customer data",
        methodology: "Cloud-native penetration testing",
      },
    ],
  },
  {
    slug: "vulnerability-assessment",
    title: "Vulnerability Assessment & Risk Analysis",
    description: "Identify security gaps, assess impact, and get clear recommendations to reduce risk.",
    shortDescription: "Find security gaps and assess their business impact",
    icon: Search,
    color: "text-[#7C3AED]",
    glowClass: "neon-glow-purple",
    fullContent: `Comprehensive vulnerability assessment services identify and prioritize security weaknesses across your entire infrastructure. We scan systems, applications, and networks to discover misconfigurations, unpatched software, and security control gaps.`,
    benefits: [
      "Complete inventory of security vulnerabilities",
      "Risk-based prioritization",
      "Clear impact analysis for each finding",
      "Actionable remediation steps",
    ],
    process: [
      "Asset Discovery & Inventory",
      "Vulnerability Scanning",
      "Manual Verification",
      "Risk Classification",
      "Report Generation",
    ],
    portfolio: [
      {
        id: 1,
        title: "Enterprise Network Assessment",
        client: "Government Agency",
        result: "Identified 2,400+ vulnerabilities, 89 critical issues",
        methodology: "Network-wide vulnerability assessment",
      },
      {
        id: 2,
        title: "Application Security Audit",
        client: "Healthcare Provider",
        result: "Found HIPAA compliance gaps and 15 high-risk flaws",
        methodology: "Application vulnerability scanning",
      },
      {
        id: 3,
        title: "Cloud Security Posture Review",
        client: "Tech Startup",
        result: "Revealed misconfigurations affecting 500+ users",
        methodology: "Cloud infrastructure assessment",
      },
    ],
  },
  {
    slug: "secure-software-development",
    title: "Secure Software Development",
    description: "We design and build software with security baked in—from architecture to deployment.",
    shortDescription: "Build secure applications from the ground up",
    icon: Lock,
    color: "text-[#E11D2E]",
    glowClass: "neon-glow-red",
    fullContent: `Our secure development services integrate security throughout the entire software development lifecycle. From threat modeling and secure design to code review and secure deployment, we ensure your applications are built to resist attacks.`,
    benefits: [
      "Security built into development process",
      "Reduced vulnerability remediation costs",
      "Compliance with industry standards",
      "Faster, more secure deployments",
    ],
    process: [
      "Threat Modeling & Design Review",
      "Secure Coding Standards",
      "Code Review & Analysis",
      "Security Testing Integration",
      "Secure Deployment Pipeline",
    ],
    portfolio: [
      {
        id: 1,
        title: "Fintech Payment Platform",
        client: "Financial Services Startup",
        result: "Delivered PCI-DSS compliant payment system with zero vulnerabilities",
        methodology: "SDLC security integration",
      },
      {
        id: 2,
        title: "Healthcare Data Analytics Tool",
        client: "Medical Research Org",
        result: "Built HIPAA-compliant system with end-to-end encryption",
        methodology: "Secure software architecture",
      },
      {
        id: 3,
        title: "IoT Device Management Platform",
        client: "Industrial Tech Company",
        result: "Implemented firmware security with OTA update capability",
        methodology: "Embedded systems security",
      },
    ],
  },
  {
    slug: "product-design",
    title: "Product Design (UI/UX & Security-First Design)",
    description: "Creating user-friendly, secure digital products that balance usability with protection.",
    shortDescription: "Design beautiful products that are secure by default",
    icon: IconDeviceDesktop,
    color: "text-[#38BDF8]",
    glowClass: "neon-glow-blue",
    fullContent: `We design digital products that don't compromise between security and usability. Our security-first design approach ensures your users are protected while enjoying a seamless experience.`,
    benefits: [
      "Security integrated into user experience",
      "Better adoption of security practices",
      "Reduced user friction for security features",
      "Professional, modern aesthetics",
    ],
    process: [
      "Security Requirements Analysis",
      "Threat-driven UX Design",
      "Secure Component Library Development",
      "User Testing & Iteration",
      "Design System Documentation",
    ],
    portfolio: [
      {
        id: 1,
        title: "Enterprise SSO Dashboard",
        client: "B2B SaaS Company",
        result: "Designed intuitive identity management UI reducing support tickets by 60%",
        methodology: "Enterprise security UX design",
      },
      {
        id: 2,
        title: "Mobile Banking App",
        client: "FinTech Startup",
        result: "Created secure yet simple mobile experience with biometric auth",
        methodology: "Mobile security design",
      },
      {
        id: 3,
        title: "Data Privacy Control Panel",
        client: "Privacy-First SaaS",
        result: "Designed clear consent management UI improving user understanding",
        methodology: "Privacy-centric UI/UX",
      },
    ],
  },
  {
    slug: "training-webinars",
    title: "Cybersecurity Training & Webinars",
    description: "Practical training for students, developers, and professionals—from beginner to advanced levels.",
    shortDescription: "Learn cybersecurity from industry experts",
    icon: Presentation,
    color: "text-[#38BDF8]",
    glowClass: "neon-glow-blue",
    fullContent: `Hands-on training programs designed to upskill your team. We offer workshops, webinars, and mentorship covering everything from security fundamentals to advanced penetration testing and forensic analysis.`,
    benefits: [
      "Practical, hands-on learning experiences",
      "Expert instructors from the industry",
      "Flexible learning formats (online/in-person)",
      "Certificates of completion",
    ],
    process: [
      "Needs Assessment",
      "Custom Curriculum Design",
      "Interactive Training Delivery",
      "Hands-on Lab Exercises",
      "Performance Evaluation",
    ],
    trainingCategories: [
      {
        id: 1,
        name: "Beginner",
        description: "Security fundamentals and best practices",
        count: "8+ courses",
      },
      {
        id: 2,
        name: "Ethical Hacking",
        description: "Penetration testing and vulnerability analysis",
        count: "5+ courses",
      },
      {
        id: 3,
        name: "Secure Development",
        description: "Secure coding and SDLC practices",
        count: "6+ courses",
      },
      {
        id: 4,
        name: "Awareness",
        description: "Employee security awareness programs",
        count: "4+ courses",
      },
    ],
    pastTrainings: [
      {
        id: 1,
        title: "Zero-Trust Architecture Summit",
        audience: "Enterprise Security Teams",
        focus: "Identity & Access Management",
        format: "Virtual Workshop",
        attendees: 245,
      },
      {
        id: 2,
        title: "Advanced Threat Hunting & Forensics",
        audience: "SOC Analysts & Incident Responders",
        focus: "Forensic Analysis & APT Detection",
        format: "In-person 2-day Workshop",
        attendees: 42,
      },
      {
        id: 3,
        title: "Cloud Security Essentials",
        audience: "Developers & Cloud Architects",
        focus: "Cloud-native Security",
        format: "Online Course Series",
        attendees: 520,
      },
      {
        id: 4,
        title: "Secure Coding Bootcamp",
        audience: "Development Teams",
        focus: "OWASP Top 10 & Secure Development",
        format: "In-person Workshop",
        attendees: 38,
      },
      {
        id: 5,
        title: "Security Awareness Program",
        audience: "All Employees",
        focus: "Social Engineering & Best Practices",
        format: "Recorded Online Course",
        attendees: 1200,
      },
    ],
  },
  {
    slug: "security-consulting",
    title: "Security Consulting & Advisory",
    description: "Expert guidance to help organizations make smart security decisions and build resilient systems.",
    shortDescription: "Strategic security guidance for your organization",
    icon: IconUser,
    color: "text-[#7C3AED]",
    glowClass: "neon-glow-purple",
    fullContent: `Our consulting team provides strategic guidance to help you build effective security programs. We work with organizations to develop security strategies, policies, and governance frameworks aligned with business objectives.`,
    benefits: [
      "Strategic security roadmap development",
      "Risk management framework implementation",
      "Security governance and compliance",
      "Vendor security assessment",
    ],
    process: [
      "Current State Assessment",
      "Gap Analysis",
      "Strategy Development",
      "Implementation Planning",
      "Ongoing Advisory Support",
    ],
    portfolio: [
      {
        id: 1,
        title: "Security Program Build-out",
        client: "Early-stage Unicorn Startup",
        result: "Established complete security program from scratch, achieved SOC 2 in 6 months",
        methodology: "Security program development",
      },
      {
        id: 2,
        title: "Incident Response Planning",
        client: "Manufacturing Company",
        result: "Developed comprehensive IR plan, reduced MTTR from 48h to 4h",
        methodology: "Incident response consulting",
      },
      {
        id: 3,
        title: "Compliance Framework Implementation",
        client: "Healthcare Provider",
        result: "Guided HIPAA compliance journey, passed audit with 100% findings",
        methodology: "Compliance consulting",
      },
    ],
  },
]
